name: Clean workflow
on:
  workflow_dispatch: 
jobs:
  jobs_one:
    name: Clean
    runs-on: ubuntu-lastest
    steps:
      - name: Clean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ../pub/
            unalias rm
            rm -rf CMSC389T-Web-Template