name: clone workflow
on:
  workflow_dispatch:
jobs:
  jobs_one:
    name: Clone
    runs-on: ubuntu-lastest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /pub/rbui/
            git clone git@github.com:richardmbui/CMSC389T-Web-Template.git