name: delete workflow
on:
  workflow_dispatch: 
jobs:
  jobs_one:
    name: Delete
    runs-on: ubuntu-lastest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            unalias rm
            rm -rf CMSC389T-Web-Template